services:
  app:
    image: bd-law-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "6789:8080"
    
    volumes:
      - ./vector-db:/home/user/code/vector-db
    