# version: '3.8'
services:
  app:
    image: bd-law-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:7860"
    
    network_mode: host